export const types = {
  ROUTER_NAVIGATE: "ROUTER_NAVIGATE",
  ROUTER_NAVIGATE_START: "ROUTER_NAVIGATE_START",
  ROUTER_NAVIGATE_SUCCESS: "ROUTER_NAVIGATE_SUCCESS",
  ROUTER_NAVIGATE_FAILURE: "ROUTER_NAVIGATE_FAILURE"
}
